---
- hosts: ovs-xenial
  remote_user: ubuntu
  gather_facts: no
  become: yes

  tasks:
    - raw: test -e /usr/bin/python || apt-get -y update && apt-get install -y python-minimal
    - setup:

- include: ansible/test/integration/ovs.yaml
